Update version increment

diff --git a/.github/workflows/new-pull-request.yml b/.github/workflows/new-pull-request.yml
--- a/.github/workflows/new-pull-request.yml
+++ b/.github/workflows/new-pull-request.yml
@@ -19,7 +19,9 @@ jobs:
     - name: Create local changes
       run: |
         CURRENT_VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
-        NEXT_VERSION=$(echo $CURRENT_VERSION | perl -ne 'if ($_ =~ /^(\d+)\.(\d+)\.(\d+)$/) { $v = $3; $v++; print "$1.$2.$v\n" } else { print "Invalid tag format."; exit 1 }')
+        echo "CURRENT_VERSION = $CURRENT_VERSION"
+        NEXT_VERSION=$(echo $CURRENT_VERSION | perl -ne 'if ($_ =~ /^(\d+)\.(\d+)\.(\d+)$/) { $v = $2; $v++; print "$1.$v.$3\n" } else { print "Invalid tag format."; exit 1 }')
+        echo "NEXT_VERSION = $NEXT_VERSION"
         echo "::set-env name=NEXT_VERSION::$(echo $NEXT_VERSION)"
     - name: Commit files
       run: |
