Improve regex

diff --git a/.github/workflows/new-pull-request.yml b/.github/workflows/new-pull-request.yml
--- a/.github/workflows/new-pull-request.yml
+++ b/.github/workflows/new-pull-request.yml
@@ -20,7 +20,7 @@ jobs:
       run: |
         CURRENT_VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
         echo "CURRENT_VERSION = $CURRENT_VERSION"
-        NEXT_VERSION=$(echo $CURRENT_VERSION | perl -ne 'if ($_ =~ /^(\d+)\.(\d+)\.(\d+)$/) { $v = $2; $v++; print "$1.$v.0\n" } else { print "Invalid tag format."; exit 1 }')
+        NEXT_VERSION=$(echo $CURRENT_VERSION | perl -ne 'if ($_ =~ /^(\d+)\.(\d+)\.\d+$/) { $v = $2; $v++; print "$1.$v.0\n" } else { print "Invalid tag format."; exit 1 }')
         echo "NEXT_VERSION = $NEXT_VERSION"
         echo "::set-env name=NEXT_VERSION::$(echo $NEXT_VERSION)"
     - name: Empty commit
